name: Open-COBOL-ESQL tests on Ubuntu
on: [push]
jobs:
  Open-COBOL-ESQL-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5 libncurses5-dev libgmp-dev bison flex gettext automake autoconf
          sudo apt-get install -y libpq-dev postgresql postgresql-contrib

      - name: Download Open-COBOL-ESQL-1.2
        run: |
          curl -L -o Open-COBOL-ESQL-1.2.tar.gz https://github.com/opensourcecobol/Open-COBOL-ESQL/archive/refs/tags/v1.2.tar.gz
          tar zxvf Open-COBOL-ESQL-1.2.tar.gz
          
      - name: Install Open-COBOL-ESQL
        run: |
          cd Open-COBOL-ESQL-1.2
          ./configure
          C_INCLUDE_PATH=/usr/include/postgresql/ make
          sudo make install
