name: Open-COBOL-ESQL tests on Ubuntu
on: [push]
jobs:
  Open-COBOL-ESQL-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5 libncurses5-dev libgmp-dev bison flex gettext automake autoconf
          sudo apt-get install -y libpq-dev postgresql postgresql-contrib

      - name: Install opensource COBOL v1.5.2J
        run: |
          curl -L -o opensource-cobol-1.5.2J.tar.gz https://github.com/opensourcecobol/opensource-cobol/archive/refs/tags/v1.5.2J.tar.gz
          tar zxvf opensource-cobol-1.5.2J.tar.gz
          cd opensource-cobol-1.5.2J/vbisam
          ./configure --prefix=/usr/
          make
          sudo make install
          cd ../
          ./configure --prefix=/usr/ --with-vbisam
          C_INCLUDE_PATH=/usr/include/postgresql/ make
          sudo make install
          cd ../
   
      - name: Checkout Open-COBOL-ESQL
        uses: actions/checkout@v2
        with:
          path: Open-COBOL-ESQL
          
      - name: Install Open-COBOL-ESQL
        run: |
          tar zcvf Open-COBOL-ESQL.tar.gz Open-COBOL-ESQL # Without these instructions,
          rm -rf Open-COBOL-ESQL                          # the following './configure' command fails.
          tar zxvf Open-COBOL-ESQL.tar.gz                 # The cause is unknown.
          cd Open-COBOL-ESQL
          ./configure --prefix=/usr/
          make
          sudo make install
