name: Open-COBOL-ESQL tests on Ubuntu
on: [push]
jobs:
  Open-COBOL-ESQL-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: apt-get install -y build-essential libncurses5 libncurses5-dev libgmp-dev bison flex gettext automake autoconf
        run: apt-get install -y libpq-dev postgresql postgresql-contrib