name: Open-COBOL-ESQL tests on Ubuntu
on: [push]
jobs:
  Open-COBOL-ESQL-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:9.6
        ports: 
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: main_user
          POSTGRES_DB: testdb
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5 libncurses5-dev libgmp-dev bison flex gettext automake autoconf
          sudo apt-get install -y libpq-dev postgresql postgresql-contrib

      - name: Install opensource COBOL v1.5.2J
        run: |
          curl -L -o opensource-cobol-1.5.2J.tar.gz https://github.com/opensourcecobol/opensource-cobol/archive/refs/tags/v1.5.2J.tar.gz
          tar zxvf opensource-cobol-1.5.2J.tar.gz
          cd opensource-cobol-1.5.2J/vbisam
          ./configure --prefix=/usr/
          make
          sudo make install
          cd ../
          ./configure --prefix=/usr/ --with-vbisam
          make
          sudo make install
          cd ../
   
      - name: Checkout Open-COBOL-ESQL
        uses: actions/checkout@v2
        with:
          path: Open-COBOL-ESQL
          
      - name: Install Open-COBOL-ESQL
        run: |
          cd Open-COBOL-ESQL
          touch * # Without this instructions, the following './configure' command fails.
          ./configure
          C_INCLUDE_PATH=/usr/include/postgresql/ make
          sudo make install
          cd ../

      - name: Run tests
        run: |
          cd Open-COBOL-ESQL/tests
          make clean
          cp ../github/workflows/ubuntu-test-settings/atlocal atlocal
          cp ../github/workflows/ubuntu-test-settings/embed_db_info.sh embed_db_info.sh
          make
          ./basic
          ./cobol_data
          ./sql_data
          ./sqlca
          cd ../../

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-test-results
          path: Open-COBOL-ESQL/tests/*.log
