name: Open-COBOL-ESQL tests on Ubuntu with Gnu COBOL osscons patch1

on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

jobs:
  Open-COBOL-ESQL-tests:
    runs-on: ubuntu-latest
    
    # Start PostgreSQL server
    services:
      postgres:
        image: postgres:9.6
        ports: 
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: main_user
          POSTGRES_DB: testdb
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5 libncurses5-dev libgmp-dev bison flex gettext
          sudo apt-get install -y libpq-dev postgresql postgresql-contrib
          sudo apt-get install -y libncurses6 libncurses-dev ncurses-doc libgmp10 libgmp-dev m4 libtool help2man pkg-config gettext automake autoconf libxml2 libxml2-dev libxml2-utils libcjson1 libcjson-dev build-essential libdb-dev
          
      # Install vbisam
      - name: Install vbisam
        run: |
          curl -L -o opensource-cobol-1.5.2J.tar.gz https://github.com/opensourcecobol/opensource-cobol/archive/refs/tags/v1.5.2J.tar.gz
          tar zxf opensource-cobol-1.5.2J.tar.gz
          cd opensource-cobol-1.5.2J/vbisam
          ./configure --prefix=/usr/
          make
          sudo make install

      # Install GNU COBOL osscons patch1
      - name: Install GNU COBOL osscons patch1
        run: |
            curl -L -o gnucobol-osscons-patch-3.2patch1a.tar.gz https://github.com/opensourcecobol/gnucobol-osscons-patch/archive/refs/tags/3.2patch1a.tar.gz
            tar zxf gnucobol-osscons-patch-3.2patch1a.tar.gz
            cd gnucobol-osscons-patch-3.2patch1a
            ./configure --prefix=/usr/ --with-xml2 --with-cjson --with-vbisam
            make
            sudo make install

      # Checkout Open-COBOL-ESQL
      - name: Checkout Open-COBOL-ESQL
        uses: actions/checkout@v4
        with:
          path: Open-COBOL-ESQL

      # Build and Install Open-COBOL-ESQL
      - name: Install Open-COBOL-ESQL
        working-directory: Open-COBOL-ESQL
        run: |
          chmod +x ./autogen.sh && ./autogen.sh
          ./configure
          sudo make install

      # Create a log directory
      - name: Create a log directory
        run: |
          mkdir -p Open-COBOL-ESQL/log/test

      # Run Autotest
      - name: Run tests
        working-directory: Open-COBOL-ESQL/tests
        run: |
          make clean
          cp ../.github/workflows/ubuntu-test-settings/atlocal atlocal
          cp ../.github/workflows/ubuntu-test-settings/embed_db_info.sh embed_db_info.sh
          cp ../.github/workflows/ubuntu-test-settings/cobol_runner.sh cobol_runner.sh
          make
          ./basic
          ./cobol_data
          ./sql_data
          ./sqlca
          ./misc
          cp -r basic.dir cobol_data.dir sql_data.dir sqlca.dir *.log ../log/test

      # Upload test logs and the result of static checking
      - name: Archive Logs
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-log
          path: Open-COBOL-ESQL/log/*
      
      # Workflow fails if one or more test cases failed
      - name: Check test results
        run: |
          cat Open-COBOL-ESQL/tests/*.log
          [ -z "$(cat Open-COBOL-ESQL/tests/*.log | grep 'Failed tests:')" ]
