name: Open-COBOL-ESQL tests on Ubuntu
on: [push]
jobs:
  Open-COBOL-ESQL-tests:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: main_user
          POSTGRES_DB: testdb
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev postgresql postgresql-contrib expect

      - name: Setup PostgreSQL server
        run: |
          PGPASSWORD=password psql -h db -p 5432 -U main_user -d testdb -c "SELECT * FROM foo"
